// export const GET_USERS_PENDING = 'GET_USERS_PENDING';
// export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS';
// export const GET_USERS_ERROR = 'GET_USERS_ERROR';
// export const ADD_USER_PENDING = 'ADD_USER_PENDING';
// export const ADD_USER_SUCCESS = 'ADD_USER_SUCCESS';
// export const ADD_USER_ERROR = 'ADD_USER_ERROR';
// export const GIVE_POINTS_ERROR = 'GIVE_POINTS_ERROR';
// export const LOGOUT_USER_ERROR = 'LOGOUT_USER_ERROR';
// export const TAKE_POINTS_ERROR = 'TAKE_POINTS_ERROR';
// export const GIVE_POINTS_PENDING = 'GIVE_POINTS_PENDING';
// export const GIVE_POINTS_SUCCESS = 'GIVE_POINTS_SUCCESS';
// export const TAKE_POINTS_PENDING = 'TAKE_POINTS_PENDING';
// export const TAKE_POINTS_SUCCESS = 'TAKE_POINTS_SUCCESS';

export const GET_ERRORS = 'GET_ERRORS';
export const REGISTER_USER_PENDING = 'REGISTER_USER_PENDING';
export const SET_USER_PENDING = 'SET_USER_PENDING';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
